### ISSUE TITLE
[Bug] search attribute CandidateEmail is not defined

### ISSUE THREAD

**Issue by smaximoff** [temporalio/background-checks#42]
### What are you really trying to do?

I follow the instructions and it fails on step: `./run-cli bgc-company start --email your-email@example.com --package full`

### Describe the bug

When starting workflow, I get an error message: `Internal Server Error: search attribute CandidateEmail is not defined`

### Minimal Reproduction

Clone repo:
```sh
git clone git@github.com:temporalio/background-checks.git
cd background-checks
./start
```

and try to run:

```sh
./run-cli bgc-company start --email your-email@example.com --package full
```

### Environment/Versions

Latest code from main branch, commit ref f06ca38

- OS and processor: Linux on amd64
- Temporal Version: [e.g. 1.14.0?] and/or SDK version
- using Docker

**Comment by jcorry** [comment]
I have a similar issue...but the error I am getting is different. For me it is:

`BadSearchAttributes: search attribute BackgroundCheckStatus is not defined`

**Comment by pbevin** [comment]
Adding this at line 11 of `docker-compose.override.yml' fixes it. I had to also reset the app with `docker-compose down` and `./start` to make it work:

```
      - xpack.security.enabled=false
```

(This is at the end of `elasticsearch`'s `environment` stanza, right after the `ES_JAVA_OPTS` line).

The issue seems to be that elasticsearch won't accept the request to add `CandidateEmail` or `BackgroundCheckStatus` with security turned on.  PR #43 fixes this, but hasn't been merged yet.

**Comment by robholland** [comment]
ES is now removed from the setup, SQL advanced visibility is fixed in https://github.com/temporalio/background-checks/pull/47.
